/*
* Data seed script
*/


/*PATIENT*/
INSERT INTO PATIENT (PATIENTID, DOB, FNAME, LNAME, STREET, CITY, STATE, ZIP, GENDER, PUBLICSTATUS) 
VALUES (1.0, to_date('01/01/1986', 'MM/DD/YYYY'), 'Gary', 'George', '2806 Conifer Drive', 'Raleigh', 'NC', 27606.0, 'M', 'Y');

INSERT INTO PATIENT (PATIENTID, DOB, FNAME, LNAME, STREET, CITY, STATE, ZIP, GENDER, PUBLICSTATUS) 
VALUES (2.0, to_date('01/02/1986', 'MM/DD/YYYY'), 'Adnan', 'Kazi', '1234 Capability Drive', ' Raleigh', 'NC', 27655.0, 'F', 'Y');

INSERT INTO PATIENT (PATIENTID, DOB, FNAME, LNAME, STREET, CITY, STATE, ZIP, GENDER, PUBLICSTATUS) 
VALUES (3.0, to_date('01/03/1986', 'MM/DD/YYYY'), 'Neha', 'Shetty', '440 Sullivan Drive', ' Chapel Hill', 'NC', 27517.0, 'F', 'Y');

INSERT INTO PATIENT (PATIENTID, DOB, FNAME, LNAME, STREET, CITY, STATE, ZIP, GENDER, PUBLICSTATUS) 
VALUES (4.0, to_date('01/04/1986', 'MM/DD/YYYY'), 'Sheldon', 'Cooper', '2808 Avent Ferry Road', ' Raleigh', 'NC', 27616.0, 'F', 'Y');

INSERT INTO PATIENT (PATIENTID, DOB, FNAME, LNAME, STREET, CITY, STATE, ZIP, GENDER, PUBLICSTATUS) 
VALUES (5.0, to_date('01/05/1986', 'MM/DD/YYYY'), 'Michael', 'Watson', '2222 Gorman Street', ' Raleigh', 'NC', 27678.0, 'M', 'Y');

INSERT INTO PATIENT (PATIENTID, DOB, FNAME, LNAME, STREET, CITY, STATE, ZIP, GENDER, PUBLICSTATUS) 
VALUES (6.0, to_date('01/06/1986', 'MM/DD/YYYY'), 'Tom', 'Kerr', '1430 Collegeview Ave', ' Durham', 'NC', 27701.0, 'M', 'Y');

INSERT INTO PATIENT (PATIENTID, DOB, FNAME, LNAME, STREET, CITY, STATE, ZIP, GENDER, PUBLICSTATUS) 
VALUES (7.0, to_date('01/07/1986', 'MM/DD/YYYY'), 'Maya', 'Tran', '100 Brown Circle', ' Chapel Hill', 'NC', 27516.0, 'F', 'Y');

/*PROBLEMS*/
SET DEFINE OFF

INSERT INTO PROBLEMS (PROBLEMID, PATIENTID, PNAME, DTTM, END_DTTM) 
VALUES (1.0, 1.0, 'HIV ', to_date('09/30/2013 08:57', 'MM/DD/YYYY'), NULL);

INSERT INTO PROBLEMS (PROBLEMID, PATIENTID, PNAME, DTTM, END_DTTM) 
VALUES (2.0, 2.0, 'Obesity', to_date('09/30/2013 08:57', 'MM/DD/YYYY'), NULL);

INSERT INTO PROBLEMS (PROBLEMID, PATIENTID, PNAME, DTTM, END_DTTM) 
VALUES (3.0, 2.0, 'High Risk Pregnancy ', to_date('09/30/2013 08:57', 'MM/DD/YYYY'), NULL);

INSERT INTO PROBLEMS (PROBLEMID, PATIENTID, PNAME, DTTM, END_DTTM) 
VALUES (4.0, 3.0, 'Obesity', to_date('09/30/2013 08:57', 'MM/DD/YYYY'), NULL);

INSERT INTO PROBLEMS (PROBLEMID, PATIENTID, PNAME, DTTM, END_DTTM) 
VALUES (5.0, 3.0, 'High Risk Pregnancy ', to_date('09/30/2013 08:57', 'MM/DD/YYYY'), NULL);

INSERT INTO PROBLEMS (PROBLEMID, PATIENTID, PNAME, DTTM, END_DTTM) 
VALUES (6.0, 4.0, 'COPD', to_date('09/30/2013 08:57', 'MM/DD/YYYY'), NULL);

INSERT INTO PROBLEMS (PROBLEMID, PATIENTID, PNAME, DTTM, END_DTTM) 
VALUES (7.0, 4.0, 'HIV ', to_date('09/30/2013 08:57', 'MM/DD/YYYY'), NULL);

INSERT INTO PROBLEMS (PROBLEMID, PATIENTID, PNAME, DTTM, END_DTTM) 
VALUES (8.0, 5.0, 'COPD ', to_date('09/30/2013 08:57', 'MM/DD/YYYY'), NULL);

INSERT INTO PROBLEMS (PROBLEMID, PATIENTID, PNAME, DTTM, END_DTTM) 
VALUES (9.0, 6.0, 'COPD ', to_date('09/30/2013 08:57', 'MM/DD/YYYY'), NULL);

INSERT INTO PROBLEMS (PROBLEMID, PATIENTID, PNAME, DTTM, END_DTTM) 
VALUES (10.0, 6.0, 'Obesity', to_date('09/30/2013 08:57', 'MM/DD/YYYY'), NULL);

INSERT INTO PROBLEMS (PROBLEMID, PATIENTID, PNAME, DTTM, END_DTTM) 
VALUES (11.0, 7.0, 'High Risk Pregnancy ', to_date('09/30/2013 08:57', 'MM/DD/YYYY'), NULL);


/*HEALTH SUPPORTERS*/
SET DEFINE OFF

INSERT INTO HEALTHSUPPORTER (SUPPORTERID, FNAME, LNAME, CLINIC) 
VALUES (1.0, 'Altaf', 'Hussain', 'Dayview ');

INSERT INTO HEALTHSUPPORTER (SUPPORTERID, FNAME, LNAME, CLINIC) 
VALUES (2.0, 'Manu', 'Joseph', 'Dayview ');

INSERT INTO HEALTHSUPPORTER (SUPPORTERID, FNAME, LNAME, CLINIC) 
VALUES (3.0, 'Shane', 'Lee', 'Huntington ');

INSERT INTO HEALTHSUPPORTER (SUPPORTERID, FNAME, LNAME, CLINIC) 
VALUES (4.0, 'Shyam', 'Prasad', 'Huntington ');

/*HEALTH FRIEND*/
INSERT INTO HEALTHFRIEND (PATIENTID, HEALTHFRIENDID, DTTM, END_DTTM) 
VALUES (6.0, 2.0, to_date('04/01/2013', ' MM/DD/YYYY HH:MI:SS'), to_date('', ' MM/DD/YYYY HH:MI:SS'));

INSERT INTO HEALTHFRIEND (PATIENTID, HEALTHFRIENDID, DTTM, END_DTTM) 
VALUES (6.0, 5.0, to_date('03/04/2011', ' MM/DD/YYYY HH:MI:SS'), to_date('', ' MM/DD/YYYY HH:MI:SS'));

INSERT INTO HEALTHFRIEND (PATIENTID, HEALTHFRIENDID, DTTM, END_DTTM) 
VALUES (4.0, 1.0, to_date('10/12/2012', ' MM/DD/YYYY HH:MI:SS'), to_date('', ' MM/DD/YYYY HH:MI:SS'));

INSERT INTO HEALTHFRIEND (PATIENTID, HEALTHFRIENDID, DTTM, END_DTTM) 
VALUES (4.0, 5.0, to_date('01/02/2013', ' MM/DD/YYYY HH:MI:SS'), to_date('', ' MM/DD/YYYY HH:MI:SS'));

INSERT INTO HEALTHFRIEND (PATIENTID, HEALTHFRIENDID, DTTM, END_DTTM) 
VALUES (4.0, 6.0, to_date('05/04/2011', ' MM/DD/YYYY HH:MI:SS'), to_date('', ' MM/DD/YYYY HH:MI:SS'));





/*
/*Create two patients*/
/*INSERT INTO Patient VALUES (Patientids_seq.nextval, '02-Nov-92', 'John', 'Holmes', '123 Main Street', 'Ann Arbor', 'MI', 48105, 'M', 'T')*/
/*INSERT INTO Patient VALUES (Patientids_seq.nextval, '02-Nov-92', 'Adam', 'Holmes', '123 Main Street', 'Ann Arbor', 'MI', 48105, 'M', 'T')*/

/*Make Adam Holmes a friend of John Holmes*/
/*INSERT INTO HealthFriend VALUES (1,2, CURRENT_TIMESTAMP(3), NULL)*/

/*Test that a patient cannot add themselves*/
/*INSERT INTO HealthFriend VALUES (1,1, CURRENT_TIMESTAMP(3), NULL)*/

/*This construct necessary to retrieve seconds*/
/*SELECT TO_CHAR(dttm,'MM/DD/YYYY HH24:MI:SS')  FROM HealthFriend;*/

/*Create a problem for John Holmes*/
/*INSERT INTO Problems VALUES (Problems_seq.nextval, 1, 'COPD', CURRENT_TIMESTAMP(3), NULL)*/
